"""Initial migration

Revision ID: 0a6e7adb3593
Revises: 
Create Date: 2025-01-09 13:10:11.440618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6e7adb3593'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_drugs_id', table_name='drugs')
    op.drop_table('drugs')
    op.drop_index('ix_pharmacies_id', table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_index('ix_inventory_id', table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('drug_id', sa.INTEGER(), nullable=False),
    sa.Column('pharmacy_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('expiration_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_id', 'inventory', ['id'], unique=False)
    op.create_table('pharmacies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.Column('specialization', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pharmacies_id', 'pharmacies', ['id'], unique=False)
    op.create_table('drugs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(), nullable=False),
    sa.Column('dosage', sa.VARCHAR(), nullable=False),
    sa.Column('indications', sa.VARCHAR(), nullable=True),
    sa.Column('contraindications', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drugs_id', 'drugs', ['id'], unique=False)
    # ### end Alembic commands ###
